### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by tedil** [vembrane/vembrane#64]
- [ ] Handle `FORMAT` properly (and make it easy to use)
  - [ ] Parse genotyping info from `FORMAT` (perhaps something along the lines of [GenotypeArray](https://scikit-allel.readthedocs.io/en/stable/model/ndarray.html?highlight=genotypearray#allel.GenotypeArray))
- [ ] For performance improvements choose either of:
  - [ ] AST parsing (https://github.com/vembrane/vembrane/pull/61)
  - [ ] lazy `dict.__getitem__` lookups (https://github.com/vembrane/vembrane/pull/63)
